config/routes.rb
Rails.application.routes.draw do
  root :to => "students#index"
  resources :exams, only: [:show]
  resources :students, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
    has_many :student_exam_results
    has_many :students, through: :student_exam_results
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :student_exam_results
    has_many :exams, through: :student_exam_results
end

app/models/student_exam_result.rb
class StudentExamResult < ApplicationRecord
    belongs_to :student 
    belongs_to :exam
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
    def show
        @exam = Exam.find(params[:id])
    end 
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    
    def index
        @students = Student.all
    end 

    def show
        @student = Student.find(params[:id])
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/student_exam_results_helper.rb
module StudentExamResultsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/exams/show.html.erb
<div class="container" align='center'>
    <h1><%= @exam.title %> Student Results </h1>
</div>

<div class="container" align='center'>
    <table class="table table-hover">
        <tr>
            <th>Student Name</th>
            <th>Score</th>
        </tr>
        <% @exam.students.each do |student| %>
            <tr>
                <td><%= link_to student.firstName + " " + student.lastName, student_path(student)%></td>
                <td><%=(@exam.student_exam_results.find_by(student_id: student.id).marksObtained.to_f / @exam.totalMarks.to_f * 100).round%>%</td>
            </tr>
        <% end %>
    </table>
</div>

<div class='container' align='center'>
  <%= link_to '<button type="button" class="btn btn-primary">Dashboard</button>'.html_safe, root_path%>
</div>

<!-- Exam Show View (/exams/1):
Update the exam show view to show the percentage of mark Obtained achieved by all students in that exam. -->
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PulseSecure</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<div class="container" align='center'>
    <h1> Student Exam Results </h1>
</div>

<div class="container" align='center'>
    <table class="table table-hover">
        <tr>
            <th>Student Name</th>
            <th>Average Score (all exams)</th>
        </tr>
        <% @students.each do |student| %>
            <tr>
                <td><%= link_to student.firstName + " " + student.lastName, student_path(student)%></td>
                <% grades = []%>
                <% student.student_exam_results.each do |result|%>
                    <% grades << result.marksObtained%>
                <% end %>
                <td><%= (grades.sum.to_f / grades.count)%>%</td>
            </tr>
        <% end %>
    </table>
</div>




<!-- Examination Dashboard (/):
Create a view to show the summed-up score as percentage of each student across all the exams that the student has appeared in.-->

app/views/students/show.html.erb
<div class="container" align='center'>
    <h1><%=@student.firstName%> <%=@student.lastName%>'s Exam Scores</h1>
</div>

<div class="container" align='center'>
    <table class="table table-hover">
        <tr>
            <th>Exam Name</th>
            <th>Score</th>
        </tr>
        <% @student.exams.each do |exam| %>
            <tr>
                <td><%= link_to exam.title, exam_path(exam) %></td>
                <td><%= (@student.student_exam_results.find_by(exam_id: exam.id).marksObtained.to_f / exam.totalMarks.to_f * 100).round  %>%</td>
            </tr>
        <% end %>
    </table>
</div>

<div class='container' align='center'>
    <%= link_to '<button type="button" class="btn btn-primary">Dashboard</button>'.html_safe, root_path%>
</div>

<!-- Student Show View (/students/1):
Update the student show view to show all the Exams given by the student and the marks obtained as percentage for each exam. -->